export default {
  SPLASH: 'SPLASH',
  ONBOARDING: 'ONBOARDING',
  HOME_SCREEN: 'HOME_SCREEN',
  WELCOME: 'WELCOME',
  REGISTER: 'REGISTER',
  OTP_VERIFICATION: 'OTP_VERIFICATION',
  PROFESSIONAL_INFO: 'PROFESSIONAL_INFO',
  HABIT: 'HABIT',
  Add_Prompt:'ADD_PROMPT',
  Photo_Verify: 'PHOTO_VERIFY'
};
