export default {
  SPLASH: 'SPLASH',
  ONBOARDING: 'ONBOARDING',
  HOME_SCREEN: 'HOME_SCREEN',
  WELCOME: 'WELCOME',
  REGISTER: 'REGISTER',
  OTP_VERIFICATION: 'OTP_VERIFICATION',
  PROFESSIONAL_INFO: 'PROFESSIONAL_INFO',
};
